sourceColsV1 = """
usr_uuid,
usr_prof_typ,
dvc_did,
pd_htl_id,
usr_mcid,
meta_rq_id ,
meta_rw_id,
meta_rw_id_srvr,
meta_rw_id_clnt,
meta_act_cntnt,
meta_fnnl_step,
meta_usr_agnt,
meta_timezone,
meta_pg_nm_full ,
meta_pg_nm,
meta_lob_nm,
meta_act_nm,
meta_pg_tm_intvl ,
meta_cmpny_id,
meta_clnt_ip,
meta_env,
srch_trvl_purp_optd ,
srch_ap ,
srch_rsq ,
srch_rm_tot ,
srch_los ,
srch_guest_adult ,
srch_rm_nghts ,
srch_trvl_purp ,
srch_guest_tot ,
srch_typ ,
srch_checkin_dt ,
srch_checkout_dt ,
srch_sty_area ,
srch_sty_cty ,
srch_sty_city ,
srch_guest_child ,
prc_surge_prcnt,
dvc_type ,
dvc_os ,
prc_wal_bal,
bkg_mlt_rm,
pd_htl_cty ,
cast(pd_disp_sell_amt_dis as double) as  pd_disp_sell_amt_dis_main,
cast(pd_disp_sell_amt as double) as pd_disp_sell_amt_main,
exp_id ,
exp_rnk_ordr ,
exp_pol_ver,
exp_pol_id,
pd_htl_fc,
pd_htl_pah,
usr_omni_vid ,
sess_mmt_id ,
sess_vst_no,
fltr_price,
fltr_clr_all,
srt_ordr ,
srt_by ,
dvc_g_city,
dvc_os_ver ,
dvc_app_ver ,
cpn_code,
bkg_txn_id,
prc_amt_chrgd,
usr_wal_bns_bal,
usr_wal_plus_bal,
usr_wal_real_bal,
prc_surge_applcbl_on,
pd_htl_city_sold_out,
pd_htl_sold_out,
exp_disp_prc,
exp_disp_prc_multiplier,
prc_disp_amt_wo_dis_srvr,
prc_disp_amt_w_dis_srvr,
exp_disp_prc_tax_included,
exp_city_tax_included,
prc_mkp_amt,
prc_commission,
prc_profit,
concat_ws(',',bkg_chld_id)  as bkg_chld_id_arr,
concat_ws(',',fltr_htl_img_tag_clckd)  as filter_htl_img_tag_clckd_arr,
concat_ws(',',fltr_prop_typ)  as filter_prop_type_arr,
concat_ws(',',fltr_star)  as filter_star_arr,
concat_ws(',',fltr_loc)  as filter_loc_arr,
concat_ws(',',fltr_aminities)  as filter_amenities_arr,
concat_ws(',',fltr_appld)  as filter_applied_arr,
concat_ws(',',fltr_rmvd)  as filter_removed_arr,
concat_ws(',',fltr_htl_rvw_appld)  as filter_htl_rvw_appld_arr,
concat_ws(',',fltr_htl_rm_slctns)  as filter_htl_rm_slctns_arr,
concat_ws(',',fltr_usr_rating)  as filter_usr_rating_arr,
prc_htl_base_prc,
prc_hot_disc,
pd_htl_rm_nm,
pd_htl_rm_typ,
prc_aaj_ka_bhao_flg,
prc_absrpn_amt,
prc_extrapax_amt,
prc_mkpsrv_fee,
prc_pay_mod,
prc_sell_amt_w_tax,
prc_sell_amt_wo_tax,
prc_div_fac,
from_unixtime(meta_prcssr_ts/1000) as record_processed_ts,
from_unixtime(m124/1000) as record_pdt_ts,
from_unixtime(m123/1000) as record_client_ts,
from_unixtime(m124/1000,'YYYY-MM-dd') as browsing_date,
usr_intnd_scr,
'' as srch_typ_loc,
'' as srch_txt,
pd_supplr_cd,
pd_htl_srvr_ls,
pd_htl_trff_srvr_ls,
pd_htl_dtl_disp,
prc_tax_htl,
prc_wal_amt,
cpn_resp_ls,
'' as locus,
'' as room_code,
'' as pd_htl_rm_cd,
'' as pd_htl_rt_plan_cd """.strip()


sourceColsV2 = """
usr_uuid,
usr_prof_typ,
dvc_did,
pd_htl_id,
usr_mcid,
meta_rq_id ,
meta_rw_id,
meta_rw_id_srvr,
meta_rw_id_clnt,
meta_act_cntnt,
meta_fnnl_step,
meta_usr_agnt,
meta_timezone,
meta_pg_nm_full ,
meta_pg_nm,
meta_lob_nm,
meta_act_nm,
meta_pg_tm_intvl ,
meta_cmpny_id,
meta_clnt_ip,
meta_env,
srch_trvl_purp_optd ,
srch_ap ,
srch_rsq ,
srch_rm_tot ,
srch_los ,
srch_guest_adult ,
srch_rm_nghts ,
srch_trvl_purp ,
srch_guest_tot ,
srch_typ ,
srch_checkin_dt ,
srch_checkout_dt ,
srch_sty_area ,
srch_sty_cty ,
srch_sty_city ,
srch_guest_child ,
prc_surge_prcnt,
dvc_type ,
dvc_os ,
prc_wal_bal,
bkg_mlt_rm,
pd_htl_cty ,
cast(pd_disp_sell_amt_dis as double) as  pd_disp_sell_amt_dis_main,
cast(pd_disp_sell_amt as double) as pd_disp_sell_amt_main,
exp_id ,
exp_rnk_ordr ,
exp_pol_ver,
exp_pol_id,
pd_htl_fc,
pd_htl_pah,
usr_omni_vid ,
sess_mmt_id ,
sess_vst_no,
fltr_price,
fltr_clr_all,
srt_ordr ,
srt_by ,
dvc_g_city,
dvc_os_ver ,
dvc_app_ver ,
cpn_code,
bkg_txn_id,
prc_amt_chrgd,
usr_wal_bns_bal,
usr_wal_plus_bal,
usr_wal_real_bal,
prc_surge_applcbl_on,
pd_htl_city_sold_out,
pd_htl_sold_out,
exp_disp_prc,
exp_disp_prc_multiplier,
prc_disp_amt_wo_dis_srvr,
prc_disp_amt_w_dis_srvr,
exp_disp_prc_tax_included,
exp_city_tax_included,
prc_mkp_amt,
prc_commission,
prc_profit,
concat_ws(',',bkg_chld_id)  as bkg_chld_id_arr,
concat_ws(',',fltr_htl_img_tag_clckd)  as filter_htl_img_tag_clckd_arr,
concat_ws(',',fltr_prop_typ)  as filter_prop_type_arr,
concat_ws(',',fltr_star)  as filter_star_arr,
concat_ws(',',fltr_loc)  as filter_loc_arr,
concat_ws(',',fltr_aminities)  as filter_amenities_arr,
concat_ws(',',fltr_appld)  as filter_applied_arr,
concat_ws(',',fltr_rmvd)  as filter_removed_arr,
concat_ws(',',fltr_htl_rvw_appld)  as filter_htl_rvw_appld_arr,
concat_ws(',',fltr_htl_rm_slctns)  as filter_htl_rm_slctns_arr,
concat_ws(',',fltr_usr_rating)  as filter_usr_rating_arr,
prc_htl_base_prc,
prc_hot_disc,
pd_htl_rm_nm,
pd_htl_rm_typ,
prc_aaj_ka_bhao_flg,
prc_absrpn_amt,
prc_extrapax_amt,
prc_mkpsrv_fee,
prc_pay_mod,
prc_sell_amt_w_tax,
prc_sell_amt_wo_tax,
prc_div_fac,
from_unixtime(meta_prcssr_ts/1000) as record_processed_ts,
from_unixtime(m124/1000) as record_pdt_ts,
from_unixtime(m123/1000) as record_client_ts,
from_unixtime(m124/1000,'YYYY-MM-dd') as browsing_date,
usr_intnd_scr,
srch_typ_loc,
srch_txt,
pd_supplr_cd,
pd_htl_srvr_ls,
pd_htl_trff_srvr_ls,
pd_htl_dtl_disp,
prc_tax_htl,
prc_wal_amt,
cpn_resp_ls,
locus,
'' as room_code,
'' as pd_htl_rm_cd,
'' as pd_htl_rt_plan_cd,
domain_sbu,
domain_country,
domain_currency,
domain_language,
funnel_source,
property_type,
usr_src_city as user_source_city,
usr_src_country as user_source_country,
retry_count,
no_hotels_recv as hotels_received_count,
no_hotels_req as hotels_requested_count,
pd_amenity_count as amenity_count,
pd_image_count as image_count,
pd_room_level_review_count as room_level_review_count,
pd_supplier_code as supplier_code,
pd_supplier_room_code as supplier_room_code """.strip()


detailTariffCols = """
tr.col.pd_htl_rm_cd as dtl_pd_htl_rm_cd,
tr.col.prc_tax_htl as dtl_prc_tax_htl,
tr.col.pd_htl_rm_nm as dtl_pd_htl_rm_nm ,
tr.col.pd_htl_rm_typ as dtl_pd_htl_rm_typ,
tr.col.cpn_resp_trff_ls,
tr.col.pd_htl_rt_plan_cd as dtl_pd_htl_rt_plan_cd,
tr.col.pd_htl_meal_plan,
tr.col.prc_mkpsrv_fee as dtl_prc_mkpsrv_fee,
tr.col.prc_pay_mod as dtl_prc_pay_mod,
tr.col.prc_div_fac as dtl_prc_div_fac,
tr.col.exp_disp_prc as dtl_exp_disp_prc,
tr.col.prc_disp_amt_wo_dis_srvr as dtl_prc_disp_amt_wo_dis_srvr,
tr.col.prc_disp_amt_w_dis_srvr as dtl_prc_disp_amt_w_dis_srvr,
tr.col.exp_disp_prc_multiplier as dtl_exp_disp_prc_multiplier,
tr.col.prc_extrapax_amt as dtl_prc_extrapax_amt,
tr.col.prc_hot_disc as dtl_prc_hot_disc,
tr.col.prc_mkp_amt as dtl_prc_mkp_amt,
tr.col.prc_htl_base_prc as dtl_prc_htl_base_prc,
tr.col.prc_wal_amt as dtl_prc_wal_amt,
tr.col.exp_disp_prc_tax_included as dtl_exp_disp_prc_tax_included,
tr.col.prc_sell_amt_wo_tax as dtl_prc_sell_amt_wo_tax,
tr.col.prc_absrpn_amt as dtl_prc_absrpn_amt,
tr.col.prc_sell_amt_w_tax as  dtl_prc_sell_amt_w_tax,
tr.col.prc_aaj_ka_bhao_flg as dtl_prc_aaj_ka_bhao_flg,
tr.col.prc_commission as dtl_prc_commission,
tr.col.prc_profit as dtl_prc_profit,
tr.col.exp_city_tax_included as dtl_exp_city_tax_included,
tr.col.pd_supplr_cd as dtl_pd_supplr_cd,
tr.col.pd_htl_lowest_trff """.strip()


#  cp.col.cpn_gr_sp_discount, - Present in cpn_resp_htl_ls but not present in "cpn_resp_trff_ls" for detail fnnl
couponCols = """
cp.col.cpn_dd_surge_amt,
cp.col.cpn_wal_intnsty_prcnt,
cp.col.cpn_wal_ded_amt,
cp.col.cpn_blckd_m,
cp.col.cpn_spl_promo,
cp.col.cpn_cd,
cp.col.cpn_amt,
cp.col.cpn_orig_amt,
cp.col.cpn_dbl_dis,
cp.col.cpn_cashbck_amt,
cp.col.cpn_mode_typ,
cp.col.cpn_status,
cp.col.cpn_wal_pls_amt_ded,
concat_ws(',',cp.col.cpn_dis_types)  as cpn_dis_types_arr,
cp.col.prc_hotelier_coupon_discount,
cp.col.prc_hotelier_gst_discount,
cp.col.prc_brin_offer_price,
cp.col.cpn_dd_applcbl """.strip()

couponColsPosexplodeTest = """
cp.cpn_dd_surge_amt,
cp.cpn_wal_intnsty_prcnt,
cp.cpn_wal_ded_amt,
cp.cpn_blckd_m,
cp.cpn_spl_promo,
cp.cpn_cd,
cp.cpn_amt,
cp.cpn_orig_amt,
cp.cpn_dbl_dis,
cp.cpn_cashbck_amt,
cp.cpn_mode_typ,
cp.cpn_status,
cp.cpn_wal_pls_amt_ded,
concat_ws(',',cp.cpn_dis_types)  as cpn_dis_types_arr,
cp.prc_hotelier_coupon_discount,
cp.prc_hotelier_gst_discount,
cp.prc_brin_offer_price,
cp.cpn_dd_applcbl """.strip()

requestFileExtraCols = """
'' as cpn_resp_trff_ls,
'' as pd_htl_meal_plan
 """

nonDisplayCols = """
cast('' as integer) as pd_htl_rnk_disp,
cast('' as boolean) as pd_htl_sold_out_htdsp,
cast('' as boolean) as pd_htl_shrtlstd_htdsp,
cast('' as boolean) as pd_htl_pah_htdsp,
cast('' as boolean) as pd_htl_fc_htdsp,
cast('' as boolean) as pd_htl_mmt_assrd_htdsp,
cast('' as double) as  pd_htl_loc_mtch_prcnt_htdsp,
cast('' as double) as pd_htl_rt_disp_htdsp,
cast('' as double) as pd_disp_sell_amt_htdsp,
cast('' as double) as pd_disp_sell_amt_dis_htdsp,
cast('' as integer) as pos,
'' as pd_htl_id_htdsp
 """.strip()


displayCols = """
pos ,
d.pd_htl_id as pd_htl_id_htdsp,
d.pd_htl_rnk_disp,
d.pd_htl_sold_out as pd_htl_sold_out_htdsp,
d.pd_htl_shrtlstd as pd_htl_shrtlstd_htdsp,
d.pd_htl_pah as pd_htl_pah_htdsp,
d.pd_htl_disp_tags as pd_htl_disp_tags_htdsp,
d.pd_htl_img_disp as pd_htl_img_disp_dtldsp,
d.pd_htl_fc as pd_htl_fc_htdsp,
d.pd_htl_cat_ls as pd_htl_cat_ls_htdsp,
d.pd_htl_mmt_assrd as pd_htl_mmt_assrd_htdsp,
d.pd_htl_loc_mtch_prcnt as pd_htl_loc_mtch_prcnt_htdsp,
d.pd_htl_rt_disp as pd_htl_rt_disp_htdsp,
cast(d.pd_disp_sell_amt as double) as pd_disp_sell_amt_htdsp,
cast(d.pd_disp_sell_amt_dis as double) as pd_disp_sell_amt_dis_htdsp
 """.strip()

#  TODO: Check ls_pd_htl_lowest_trff not getting into table
nonListingCols = """
'' as ls_pd_htl_cty,
cast('' as boolean) as ls_pd_htl_sold_out,
cast('' as boolean) as ls_pd_htl_fc,
'' as ls_prc_surge_applcbl_on,
cast('' as double) as ls_prc_surge_prcnt,
cast('' as boolean)  as ls_pd_htl_lowest_trff,
'' as ls_pd_supplr_cd,
'' as ls_pd_srvr_loc_st_cd,
'' as ls_pd_srvr_loc_city_cd,
array() as ls_pd_srvr_loc_reg_cds,
'' as ls_pd_srvr_loc_area_cds,
'' as ls_pd_srvr_loc_ctry_cd,
'' as ls_location_id,
'' as ls_exp_pol_ver,
'' as ls_exp_pol_id,
'' as ls_cpn_resp_htl_ls,
'' as ls_location_type
 """.strip()


listingColsV1 = """
ls.col.pd_htl_cty as ls_pd_htl_cty,
ls.col.pd_htl_sold_out as ls_pd_htl_sold_out,
ls.col.pd_htl_meal_plan as ls_pd_htl_meal_plan,
ls.col.pd_htl_rm_cd as ls_pd_htl_rm_cd,
ls.col.pd_htl_rt_plan_cd as ls_pd_htl_rt_plan_cd,
ls.col.pd_htl_fc as ls_pd_htl_fc,
ls.col.prc_mkpsrv_fee as ls_prc_mkpsrv_fee,
ls.col.prc_pay_mod as ls_prc_pay_mod,
ls.col.prc_div_fac as ls_prc_div_fac,
ls.col.prc_extrapax_amt as ls_prc_extrapax_amt,
ls.col.prc_hot_disc as ls_prc_hot_disc,
ls.col.prc_mkp_amt as ls_prc_mkp_amt,
ls.col.prc_sell_amt_wo_tax as ls_prc_sell_amt_wo_tax,
ls.col.prc_surge_applcbl_on as ls_prc_surge_applcbl_on,
ls.col.prc_surge_prcnt as ls_prc_surge_prcnt,
ls.col.prc_absrpn_amt as ls_prc_absrpn_amt,
ls.col.prc_sell_amt_w_tax as ls_prc_sell_amt_w_tax,
ls.col.prc_disp_amt_wo_dis_srvr as ls_prc_disp_amt_wo_dis_srvr,
ls.col.prc_disp_amt_w_dis_srvr as ls_prc_disp_amt_w_dis_srvr,
ls.col.exp_disp_prc as ls_exp_disp_prc,
ls.col.exp_disp_prc_multiplier as ls_exp_disp_prc_multiplier,
ls.col.exp_disp_prc_tax_included as ls_exp_disp_prc_tax_included,
ls.col.prc_commission as ls_prc_commission,
ls.col.prc_profit as ls_prc_profit,
ls.col.prc_htl_base_prc as ls_prc_htl_base_prc,
ls.col.exp_city_tax_included as ls_exp_city_tax_included,
ls.col.pd_htl_lowest_trff as ls_pd_htl_lowest_trff,
ls.col.pd_supplr_cd as ls_pd_supplr_cd,
ls.col.prc_tax_htl as ls_prc_tax_htl,
ls.col.prc_wal_amt as ls_prc_wal_amt,
ls.col.exp_pol_ver as ls_exp_pol_ver,
ls.col.exp_pol_id as ls_exp_pol_id,
ls.col.cpn_resp_htl_ls as ls_cpn_resp_htl_ls,
ls.col.locus_hotel.pd_srvr_loc_st_cd as ls_pd_srvr_loc_st_cd,
ls.col.locus_hotel.pd_srvr_loc_city_cd as ls_pd_srvr_loc_city_cd,
ls.col.locus_hotel.pd_srvr_loc_reg_cds as ls_pd_srvr_loc_reg_cds,
ls.col.locus_hotel.pd_srvr_loc_area_cds as ls_pd_srvr_loc_area_cds,
ls.col.locus_hotel.pd_srvr_loc_ctry_cd as ls_pd_srvr_loc_ctry_cd,
ls.col.locus_hotel.location_id as ls_location_id,
ls.col.locus_hotel.location_type as ls_location_type,
'' as ls_pd_htl_rank,
'' as ls_pd_is_htl_srch """.strip()


listingColsV2 = """
ls.col.pd_htl_cty as ls_pd_htl_cty,
ls.col.pd_htl_sold_out as ls_pd_htl_sold_out,
ls.col.pd_htl_meal_plan as ls_pd_htl_meal_plan,
ls.col.pd_htl_rm_cd as ls_pd_htl_rm_cd,
ls.col.pd_htl_rt_plan_cd as ls_pd_htl_rt_plan_cd,
ls.col.pd_htl_fc as ls_pd_htl_fc,
ls.col.prc_mkpsrv_fee as ls_prc_mkpsrv_fee,
ls.col.prc_pay_mod as ls_prc_pay_mod,
ls.col.prc_div_fac as ls_prc_div_fac,
ls.col.prc_extrapax_amt as ls_prc_extrapax_amt,
ls.col.prc_hot_disc as ls_prc_hot_disc,
ls.col.prc_mkp_amt as ls_prc_mkp_amt,
ls.col.prc_sell_amt_wo_tax as ls_prc_sell_amt_wo_tax,
ls.col.prc_surge_applcbl_on as ls_prc_surge_applcbl_on,
ls.col.prc_surge_prcnt as ls_prc_surge_prcnt,
ls.col.prc_absrpn_amt as ls_prc_absrpn_amt,
ls.col.prc_sell_amt_w_tax as ls_prc_sell_amt_w_tax,
ls.col.prc_disp_amt_wo_dis_srvr as ls_prc_disp_amt_wo_dis_srvr,
ls.col.prc_disp_amt_w_dis_srvr as ls_prc_disp_amt_w_dis_srvr,
ls.col.exp_disp_prc as ls_exp_disp_prc,
ls.col.exp_disp_prc_multiplier as ls_exp_disp_prc_multiplier,
ls.col.exp_disp_prc_tax_included as ls_exp_disp_prc_tax_included,
ls.col.prc_commission as ls_prc_commission,
ls.col.prc_profit as ls_prc_profit,
ls.col.prc_htl_base_prc as ls_prc_htl_base_prc,
ls.col.exp_city_tax_included as ls_exp_city_tax_included,
ls.col.pd_htl_lowest_trff as ls_pd_htl_lowest_trff,
ls.col.pd_supplr_cd as ls_pd_supplr_cd,
ls.col.prc_tax_htl as ls_prc_tax_htl,
ls.col.prc_wal_amt as ls_prc_wal_amt,
ls.col.exp_pol_ver as ls_exp_pol_ver,
ls.col.exp_pol_id as ls_exp_pol_id,
ls.col.cpn_resp_htl_ls as ls_cpn_resp_htl_ls,
ls.col.locus_hotel.pd_srvr_loc_st_cd as ls_pd_srvr_loc_st_cd,
ls.col.locus_hotel.pd_srvr_loc_city_cd as ls_pd_srvr_loc_city_cd,
ls.col.locus_hotel.pd_srvr_loc_reg_cds as ls_pd_srvr_loc_reg_cds,
ls.col.locus_hotel.pd_srvr_loc_area_cds as ls_pd_srvr_loc_area_cds,
ls.col.locus_hotel.pd_srvr_loc_ctry_cd as ls_pd_srvr_loc_ctry_cd,
ls.col.locus_hotel.location_id as ls_location_id,
ls.col.locus_hotel.location_type as ls_location_type,
ls.col.pd_htl_rank as ls_pd_htl_rank,
ls.col.pd_is_htl_srch as ls_pd_is_htl_srch """.strip()


detailRenamedCols = """
CASE WHEN meta_fnnl_step=='listing' THEN pd_htl_id_htdsp  ELSE pd_htl_id END  as hotel_id,
usr_uuid as uuid,
upper(usr_prof_typ) as profile_type,
dvc_did as device_id,
usr_mcid as user_mcid,
pd_htl_id,
pd_htl_id_htdsp,
lower(meta_fnnl_step) as meta_fnnl_step,
usr_omni_vid as visitor_id,
meta_rq_id as correlation_key,
record_processed_ts,
record_pdt_ts,
record_client_ts,
browsing_date,
meta_rw_id as meta_row_id,
meta_rw_id_srvr as meta_row_id_srvr,
meta_rw_id_clnt as meta_row_id_clnt,
meta_act_cntnt,
meta_usr_agnt as meta_user_agent,
meta_timezone,
meta_pg_nm_full as page_name,
meta_pg_nm as pg_nm_omniture,
meta_lob_nm as lob_name,
lower(meta_act_nm) as meta_activity_name,
cast(meta_pg_tm_intvl as Long) as time_spent,
meta_cmpny_id as company_id,
meta_clnt_ip as client_ip,
meta_env as env,
cast(srch_trvl_purp_optd as boolean) as query_travel_purpose_optd,
cast(srch_ap as Short) as ap,
srch_rsq as roomstayqualifier,
cast(srch_rm_tot as short) as total_rooms,
cast(srch_los as short) as length_of_stay,
cast(srch_guest_adult as short) as total_adults,
cast(srch_rm_nghts as short) as total_room_nights,
srch_trvl_purp as travel_purpose,
cast(srch_guest_tot as short) as total_guests,
srch_typ as query_type,
cast(srch_checkin_dt as date) as checkin_date,
cast(srch_checkout_dt as date) as checkout_date,
srch_sty_area as query_value,
srch_sty_cty as query_country,
srch_sty_city as query_city,
cast(srch_guest_child as short) as total_children,
CASE WHEN meta_fnnl_step=='listing' THEN ls_exp_pol_ver  ELSE exp_pol_ver END  as policy_version,
CASE WHEN meta_fnnl_step=='listing' THEN ls_exp_pol_id  ELSE exp_pol_id END  as policy_id,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_surge_prcnt  ELSE prc_surge_prcnt END  as prc_surge_prcnt,
dvc_type as device_type,
upper(dvc_os) as os,
cast(prc_wal_bal as double) as prc_wallet_balance,
cast(bkg_mlt_rm as boolean) as is_multi_room,
CASE WHEN meta_fnnl_step=='listing' THEN ls_pd_htl_cty  ELSE pd_htl_cty END  as country_code,
exp_id,
exp_rnk_ordr as exp_rnk_algo_ver,
CASE WHEN meta_fnnl_step=='listing' THEN ls_exp_pol_ver  ELSE exp_pol_ver END  as exp_pol_ver,
CASE WHEN meta_fnnl_step=='listing' THEN ls_exp_pol_id  ELSE exp_pol_id END  as exp_pol_id,
CASE WHEN meta_fnnl_step=='detail' THEN pd_htl_fc_htdsp
    ELSE
        CASE WHEN meta_fnnl_step=='listing' THEN ls_pd_htl_fc ELSE pd_htl_fc END
END as is_free_cncl,
cast(pd_htl_pah as boolean) as is_pah,
cast(usr_wal_bns_bal as double) as usr_wal_bonus_bal,
cast(usr_wal_plus_bal as double),
cast(usr_wal_real_bal as double),
usr_intnd_scr,
sess_mmt_id as session_id,
sess_vst_no as session_vst_num,
fltr_price as filter_price,
cast(fltr_clr_all as boolean) as filter_clr_all,
srt_by as applied_sort,
srt_ordr as applied_sort_order,
dvc_g_city,
dvc_os_ver as os_version,
dvc_app_ver as app_version,
cpn_code as cpn_code_main,
bkg_txn_id,
bkg_chld_id_arr,
filter_htl_img_tag_clckd_arr,
filter_prop_type_arr,
filter_star_arr,
filter_loc_arr,
filter_amenities_arr,
filter_applied_arr,
filter_removed_arr,
filter_htl_rvw_appld_arr,
filter_htl_rm_slctns_arr,
filter_usr_rating_arr,
cast(pd_htl_rnk_disp as int),
cast(pd_htl_sold_out_htdsp as boolean) as is_htl_sold_out_lstng,
cast(pd_htl_shrtlstd_htdsp as boolean) as is_htl_shrtlstd_lstng,
cast(pd_htl_pah_htdsp as boolean) as is_htl_pah_lstng,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_surge_applcbl_on  ELSE prc_surge_applcbl_on END  as prc_surge_applcbl_on,
cast(pd_htl_fc_htdsp as boolean) as is_htl_fc_lstng,
cast(pd_htl_mmt_assrd_htdsp as boolean) as is_htl_mmt_assrd_lstng,
cast(pd_htl_loc_mtch_prcnt_htdsp as double) as htl_loc_mtch_prcnt_lstng,
cast(pd_htl_rt_disp_htdsp as double) as htl_rating_disp_lstng,
cast(prc_amt_chrgd as double),
cast(pos as integer) as htl_rnk_disp_order,
CASE WHEN meta_fnnl_step=='listing' THEN pd_disp_sell_amt_htdsp       ELSE pd_disp_sell_amt_main END  as disp_sell_amt,
CASE WHEN meta_fnnl_step=='listing' THEN pd_disp_sell_amt_dis_htdsp   ELSE pd_disp_sell_amt_dis_main END  as disp_sell_amt_dis,
pd_htl_city_sold_out as is_htl_city_sold_out,
CASE WHEN meta_fnnl_step=='detail' THEN pd_htl_sold_out_htdsp
ELSE
CASE WHEN meta_fnnl_step=='listing' THEN ls_pd_htl_sold_out ELSE pd_htl_sold_out END
END as is_htl_sold_out,
srch_typ_loc as loc_search_type,
srch_txt as loc_search_text,
domain_sbu,
domain_country,
domain_currency,
domain_language,
funnel_source,
property_type,
user_source_city,
user_source_country,
retry_count,
hotels_received_count,
hotels_requested_count,
amenity_count,
image_count,
room_level_review_count,
supplier_code,
supplier_room_code """.strip()


tariffDetailRenamedCols = """
cpn_resp_trff_ls,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_pd_htl_rm_cd ELSE room_code END as room_code,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_pd_htl_rm_nm  ELSE pd_htl_rm_nm END  as room_name,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_pd_htl_rm_typ  ELSE pd_htl_rm_typ END  as room_type,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_tax_htl ELSE prc_tax_htl END as prc_tax_htl,
pd_htl_meal_plan as htl_meal_plan_code,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_pd_htl_rt_plan_cd ELSE pd_htl_rt_plan_cd END as htl_rate_plan_code,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_mkpsrv_fee ELSE prc_mkpsrv_fee END as prc_mkpsrv_fee,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_pay_mod ELSE prc_pay_mod END as prc_pay_mod,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_div_fac ELSE prc_div_fac END as prc_div_fac,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_extrapax_amt ELSE prc_extrapax_amt END as prc_extrapax_amt,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_hot_disc ELSE prc_hot_disc END as prc_hotelier_promotion,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_mkp_amt ELSE prc_mkp_amt END as prc_mmt_markup,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_htl_base_prc ELSE prc_htl_base_prc END as prc_htl_base_prc,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_sell_amt_wo_tax ELSE prc_sell_amt_wo_tax END as prc_sell_amt_wo_tax,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_absrpn_amt ELSE prc_absrpn_amt END as prc_absrpn_amt,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_sell_amt_w_tax ELSE prc_sell_amt_w_tax END as prc_sell_amt_w_tax,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_wal_amt ELSE prc_wal_amt END as prc_wal_amt,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_aaj_ka_bhao_flg  ELSE prc_aaj_ka_bhao_flg END  as prc_aaj_ka_bhao_flg,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_commission ELSE prc_commission END as prc_commission,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_profit ELSE prc_profit END as prc_profit,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_exp_city_tax_included ELSE exp_city_tax_included END as exp_city_tax_included,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_exp_disp_prc_tax_included ELSE exp_disp_prc_tax_included END as exp_disp_prc_tax_included,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_exp_disp_prc_multiplier ELSE exp_disp_prc_multiplier END as exp_disp_prc_multiplier,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_disp_amt_w_dis_srvr ELSE prc_disp_amt_w_dis_srvr END as prc_disp_amt_w_dis_srvr,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_prc_disp_amt_wo_dis_srvr ELSE prc_disp_amt_wo_dis_srvr END as prc_disp_amt_wo_dis_srvr,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_exp_disp_prc ELSE exp_disp_prc END as exp_disp_prc,
CASE WHEN meta_fnnl_step=='detail' THEN dtl_pd_supplr_cd ELSE pd_supplr_cd END as pd_supplier_code,
CAST('' as int) as srvr_hotel_rank,
'' as hotel_searched """.strip()


tariffListingRenamedCols = """
cpn_resp_trff_ls,
CASE WHEN meta_fnnl_step=='listing' THEN ls_pd_htl_rm_cd ELSE room_code END as room_code,
pd_htl_rm_nm  as room_name,
pd_htl_rm_typ as room_type,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_tax_htl ELSE prc_tax_htl END as prc_tax_htl,
CASE WHEN meta_fnnl_step=='listing' THEN ls_pd_htl_meal_plan  ELSE pd_htl_meal_plan END  as htl_meal_plan_code,
CASE WHEN meta_fnnl_step=='listing' THEN ls_pd_htl_rt_plan_cd ELSE pd_htl_rt_plan_cd END as htl_rate_plan_code,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_mkpsrv_fee ELSE prc_mkpsrv_fee END as prc_mkpsrv_fee,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_pay_mod ELSE prc_pay_mod END as prc_pay_mod,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_div_fac ELSE prc_div_fac END as prc_div_fac,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_extrapax_amt ELSE prc_extrapax_amt END as prc_extrapax_amt,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_hot_disc ELSE prc_hot_disc END as prc_hotelier_promotion,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_mkp_amt ELSE prc_mkp_amt END as prc_mmt_markup,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_htl_base_prc ELSE prc_htl_base_prc END as prc_htl_base_prc,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_sell_amt_wo_tax ELSE prc_sell_amt_wo_tax END as prc_sell_amt_wo_tax,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_absrpn_amt ELSE prc_absrpn_amt END as prc_absrpn_amt,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_sell_amt_w_tax ELSE prc_sell_amt_w_tax END as prc_sell_amt_w_tax,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_wal_amt ELSE prc_wal_amt END as prc_wal_amt,
prc_aaj_ka_bhao_flg  ,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_commission ELSE prc_commission END as prc_commission,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_profit ELSE prc_profit END as prc_profit,
CASE WHEN meta_fnnl_step=='listing' THEN ls_exp_city_tax_included ELSE exp_city_tax_included END as exp_city_tax_included,
CASE WHEN meta_fnnl_step=='listing' THEN ls_exp_disp_prc_tax_included ELSE exp_disp_prc_tax_included END as exp_disp_prc_tax_included,
CASE WHEN meta_fnnl_step=='listing' THEN ls_exp_disp_prc_multiplier ELSE exp_disp_prc_multiplier END as exp_disp_prc_multiplier,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_disp_amt_w_dis_srvr ELSE prc_disp_amt_w_dis_srvr END as prc_disp_amt_w_dis_srvr,
CASE WHEN meta_fnnl_step=='listing' THEN ls_prc_disp_amt_wo_dis_srvr ELSE prc_disp_amt_wo_dis_srvr END as prc_disp_amt_wo_dis_srvr,
CASE WHEN meta_fnnl_step=='listing' THEN ls_exp_disp_prc ELSE exp_disp_prc END as exp_disp_prc,
CASE WHEN meta_fnnl_step=='listing' THEN ls_pd_supplr_cd ELSE pd_supplr_cd END as pd_supplier_code,
cast(ls_pd_htl_rank as int) as srvr_hotel_rank,
cast(ls_pd_is_htl_srch as varchar(100)) as hotel_searched """.strip()


tariffNonListingRenamedCols = """
cpn_resp_trff_ls,
room_code ,
pd_htl_rm_nm as room_name,
pd_htl_rm_typ as room_type,
prc_tax_htl,
pd_htl_meal_plan  as htl_meal_plan_code,
pd_htl_rt_plan_cd as htl_rate_plan_code,
prc_mkpsrv_fee,
prc_pay_mod,
prc_div_fac,
prc_extrapax_amt,
prc_hot_disc as prc_hotelier_promotion,
prc_mkp_amt as prc_mmt_markup,
prc_htl_base_prc,
prc_sell_amt_wo_tax,
prc_absrpn_amt,
prc_sell_amt_w_tax,
prc_wal_amt,
prc_aaj_ka_bhao_flg,
prc_commission,
prc_profit,
exp_city_tax_included,
exp_disp_prc_tax_included,
exp_disp_prc_multiplier,
prc_disp_amt_w_dis_srvr,
prc_disp_amt_wo_dis_srvr,
exp_disp_prc,
pd_supplr_cd AS pd_supplier_code,
cast('' as int) as srvr_hotel_rank,
'' as hotel_searched """.strip()


couponRenamedCols = """
cast(cpn_dd_surge_amt as double),
cast(cpn_wal_intnsty_prcnt as double),
cast(cpn_wal_ded_amt as double),
cast(cpn_blckd_m as boolean),
cast(cpn_spl_promo as boolean),
cpn_cd,
cast(cpn_amt as double),
cast(cpn_orig_amt as double),
cast(cpn_dbl_dis as boolean),
cast(cpn_cashbck_amt as double),
cpn_mode_typ,
cpn_status,
cast(cpn_wal_pls_amt_ded as double),
cpn_dis_types_arr,
prc_hotelier_coupon_discount as cpn_hotelier_discount,
prc_hotelier_gst_discount as cpn_hotelier_gst_discount,
prc_brin_offer_price as cpn_brin_offer_price,
cpn_dd_applcbl as cpn_dd_applicable
 """.strip()


locusMainColsV1 = """
'' as pd_loc_st_code,
'' as pd_loc_city_cd,
'' as pd_loc_area_cds,
'' as pd_loc_reg_cds,
'' as pd_loc_ctry_cd,
'' as pd_is_locus,
'' as pd_srvr_loc_st_cd,
'' as pd_srvr_loc_city_cd,
'' as pd_srvr_loc_reg_cds,
'' as pd_loc_area_cds,
'' as pd_srvr_loc_ctry_cd,
'' as location_id,
'' as location_type,
'' as poi_nm,
'' as poi_ls[0].poi_cd,
'' as poi_ls[0].poi_lat,
'' as poi_ls[0].poi_long,
'' as poi_ls[0].poi_type
 """.strip()


locusMainCols = """
locus.pd_loc_st_code,
locus.pd_loc_city_cd,
locus.pd_loc_reg_cds,
locus.pd_loc_ctry_cd,
locus.pd_is_locus,
locus.pd_srvr_loc_st_cd,
locus.pd_srvr_loc_city_cd,
locus.pd_srvr_loc_reg_cds,
locus.pd_loc_area_cds,
locus.pd_srvr_loc_ctry_cd,
locus.location_id,
locus.location_type,
locus.poi_ls[0].poi_nm,
locus.poi_ls[0].poi_cd,
locus.poi_ls[0].poi_lat,
locus.poi_ls[0].poi_long,
locus.poi_ls[0].poi_type
 """.strip()


locusRenamedColsV1 = """
'' as loc_state_code,
'' as loc_city_code,
'' as loc_area_codes_arr,
'' as loc_region_codes_arr,
'' as loc_country_code,
'' as loc_is_locus,
'' as loc_state_code_srvr,
'' as loc_city_code_srvr,
'' as loc_region_codes_arr_srvr,
'' as loc_area_codes_arr_srvr,
'' as loc_country_code_srvr,
'' as loc_location_id,
'' as loc_location_type,
'' as loc_poi_name,
'' as loc_poi_code,
'' as loc_poi_lat,
'' as loc_poi_long,
'' as loc_poi_type
 """.strip()


locusRenamedColsV2 = """
locus.pd_loc_st_code as loc_state_code,
locus.pd_loc_city_cd as loc_city_code,
concat_ws(',',locus.pd_loc_area_cds)  as loc_area_codes_arr,
concat_ws(',',locus.pd_loc_reg_cds)  as loc_region_codes_arr,
locus.pd_loc_ctry_cd as loc_country_code,
locus.pd_is_locus as loc_is_locus,
CASE WHEN meta_fnnl_step=='listing' THEN ls_pd_srvr_loc_st_cd  ELSE pd_srvr_loc_st_cd END  as loc_state_code_srvr,
CASE WHEN meta_fnnl_step=='listing' THEN ls_pd_srvr_loc_city_cd  ELSE pd_srvr_loc_city_cd END  as loc_city_code_srvr,
CASE WHEN meta_fnnl_step=='listing' THEN concat_ws(',',ls_pd_srvr_loc_reg_cds) ELSE  concat_ws(',',locus.pd_srvr_loc_reg_cds) END  as loc_region_codes_arr_srvr,
CASE WHEN meta_fnnl_step=='listing' THEN concat_ws(',',ls_pd_srvr_loc_area_cds) ELSE  concat_ws(',',locus.pd_srvr_loc_area_cds) END  as loc_area_codes_arr_srvr,
CASE WHEN meta_fnnl_step=='listing' THEN ls_pd_srvr_loc_ctry_cd  ELSE pd_srvr_loc_ctry_cd END  as loc_country_code_srvr,
CASE WHEN meta_fnnl_step=='listing' THEN ls_location_id  ELSE location_id END  as loc_location_id,
CASE WHEN meta_fnnl_step=='listing' THEN ls_location_type  ELSE location_type END  as loc_location_type,
locus.poi_ls[0].poi_nm as loc_poi_name,
locus.poi_ls[0].poi_cd as loc_poi_code,
locus.poi_ls[0].poi_lat as loc_poi_lat,
locus.poi_ls[0].poi_long as loc_poi_long,
locus.poi_ls[0].poi_type as loc_poi_type,
locus.pd_loc_htl_cd as loc_hotel_code,
locus.pd_mm_applied_listing as loc_mm_applied_listing """.strip()